name: Python

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: |
          echo "Python version: ${{ matrix.python-version }}" >> version_output_${{ matrix.python-version }}.txt
          python -c "import sys; print(sys.version)" >> version_output_${{ matrix.python-version }}.txt

      - name: Upload output artifact
        uses: actions/upload-artifact@v2
        with:
          name: python-version-output-${{ matrix.python-version }}
          path: version_output_${{ matrix.python-version }}.txt
